spring:
  application:
    name: deposit

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: ${spring.datasource.currentSchema}

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    currentSchema: public
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      pool-name: pg-deposit-pool

camel:
  springboot:
    main-run-controller: true


kafka:
  group-id: deposit-app
  inner-brokers: localhost:29092

logging:
  level:
    root: INFO
    org.apache.camel: INFO
#    com.jss.camel.components: INFO
#    org.apache.http: INFO
#    org.apache.commons.httpclient: INFO
#    org.apache.coyote: INFO




