openapi: '3.0.2'
info:
  title: Async API Specification
  version: "1"

paths: { }

components:
  schemas:
    CreateProductRequestInnerEvent:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        body:
          type: object
          properties:
            sum:
              type: number
              format: decimal
          required:
            - sum
        timestamp:
          type: string
          format: date-time
          pattern: yyyy-MM-dd'T'HH:mm:ss'Z'
      required:
        - body
        - timestamp
        - id

    StatusProductResponse:
      oneOf:
        - $ref: '#/components/schemas/CreateProductResponseInnerEvent'
        - $ref: '#/components/schemas/Error'

    CreateProductResponse:
      oneOf:
        - $ref: '#/components/schemas/CreateProductResponseInnerEvent'
        - $ref: '#/components/schemas/Error'

    CreateProductResponseInnerEvent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier
        body:
          type: object
          properties:
            productId:
              type: string
              description: Unique identifier
          required:
            - sum
        timestamp:
          type: string
          format: date-time
          pattern: yyyy-MM-dd'T'HH:mm:ss'Z'
      required:
        - body
        - timestamp
        - id

    Error:
      type: object
      properties:
        code:
          type: string
          enum:
            - VALIDATION_FAILED
            - INTERNAL_SERVER_ERROR
            - NOT_FOUND
        message:
          type: string
      required:
        - code
